<a href="https://colab.research.google.com/github/shanu9540/Demofile/blob/main/python_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world


In [ ]:
a= 3
b= 5
print(a+b)

8


In [ ]:
num1 = int(input('Enter the first number: '))
num2 = int(input('Enter the second number: '))

result = num1 + num2

print("Addition =", result)

Enter the first number: 5
Enter the second number: 6
Addition = 11


In [ ]:
a=(input())
b=input()
print(a+b)
c=a+b
print(c)

In [ ]:
i = 5
while i<=50:
  print(i)
  i=i+5

5
10
15
20
25
30
35
40
45
50


In [ ]:
i = 5
while i<=50:
  print(i)
  i=i+5


5
10
15
20
25
30
35
40
45
50


In [ ]:
print('prime number from 1 to 100')
for num in range(2 , 101):
  is_prime = True

  for i in range(2, num):
    if num % i == 0:
      is_prime = False
      break
  if is_prime:
      print(num, end=" ")

prime number from 1 to 100
2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

In [ ]:
import math
print("Prime numbers from 1 to 100:")

for num in range(2, 101):
    prime = True

    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            prime = False
            break

    if prime:
        print(num, end=" ")

Prime numbers from 1 to 100:
2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

In [ ]:
a =(input("enter the first number"))
b = (input("enter the second number"))
c = (input("enter the third number"))
result = a + b + c
print("addition=" , result)


enter the first number34
enter the second number23
enter the third number45
addition= 342345


In [ ]:
import random

numbers = [10, 20, 30, 40, 50, 60]

random_number = random.choice(numbers)

print("Random Number:", random_number)

Random Number: 60


In [ ]:
a = [1, 2, 3, 5, 11]

square = [x**2 for x in a]

print("square", square)

square [1, 4, 9, 25, 121]


In [ ]:
a = ["Cat", "Dog", "Lion", "Tiger", "Elephant"]

print(a)

['Cat', 'Dog', 'Lion', 'Tiger', 'Elephant']


In [ ]:
a = ["Cat", "Dog", "Lion", "Tiger", "Elephant"]

upper_case = [x.upper() for x in a]

print(upper_case)

['CAT', 'DOG', 'LION', 'TIGER', 'ELEPHANT']


In [ ]:
a = ["Car" , "Dog" , "Lion" , "Tiger"]
upper_case = [x.upper()for x in a]
for i, value in enumerate(upper_case, start=1):
 print(i, value)

1 CAR
2 DOG
3 LION
4 TIGER


In [ ]:
a = int(input('enter the  number'))
b = 1
for i in range(b, a):
  if(i % 2 and i % 3 and i % 5 == 0):
    print(i)


enter the first number23
5


In [ ]:
a = 1
b =int(input("enter the number"))
for i in range(a ,b):
  if(i % 6 and i % 7 == 0):
    print(i)

enter the number42
7
14
21
28
35


In [ ]:
a = [1 , 2 , 6]
a.append(3)
a.append(4)
a.append(5)
print(a)

[1, 2, 6, 3, 4, 5]


In [ ]:
a = [1 , 2 , 4 , 6 ]
a.insert(4,5)
print(a)

[1, 2, 4, 6, 5]


In [ ]:
def greet():
    print("hello")
    print("hi")
    print("how are you")

greet()

hello
hi
how are you


In [ ]:


class Car:

    def __init__(self, brand, color, mileage):
        self.brand = brand
        self.color = color
        self.mileage = mileage

    def show_details(self):
        print("Car Brand :", self.brand)
        print("Car Color :", self.color)
        print("Car Mileage :", self.mileage, "km/l")


car1 = Car("Toyota", "Black", 18)

car1.show_details()

Car Brand : Toyota
Car Color : Black
Car Mileage : 18 km/l


In [ ]:
from abc import ABC, abstractmethod

class Car(ABC):
    def __init__(self, color, mileage):

        self.__color = color
        self.__mileage = mileage

    def get_color(self):
        return self.__color
    def get_mileage(self):
        return self.__mileage

    @abstractmethod
    def get_info(self):
        pass

class Tesla(Car):

    def get_info(self):
        return f"Tesla Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
class BMW(Car):

    def get_info(self):
        return f"BMW Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
class Audi(Car):

    def get_info(self):
        return f"Audi Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"

car1 = Tesla("Red", 500)
car2 = BMW("Black", 400)
car3 = Audi("White", 450)

cars = [car1, car2, car3]
for car in cars:
    print(car.get_info())

Tesla Car of Color: Red, Mileage: 500 km
BMW Car of Color: Black, Mileage: 400 km
Audi Car of Color: White, Mileage: 450 km


In [ ]:
my_list = [10, 20, 30, 40]

my_tuple = tuple(my_list)

__builtins__.print(my_tuple)

__builtins__.print(type(my_tuple))

(10, 20, 30, 40)
<class 'tuple'>


In [ ]:
list1 = [20]
list2 = [2 , 3 , 4 , 5 , 6]
list3 = list1+list2
__builtins__.print(list3)

[20, 2, 3, 4, 5, 6]


In [ ]:
import numpy as np

v1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
__builtins__.print(v1[v1 > 5])   # elements greater than 5
__builtins__.print(v1 * 2)       # multiply each element by 2
__builtins__.print(v1[1:5])      # slicing from index 1 to 4
__builtins__.print(v1[::-1])     # reverse array
__builtins__.print(v1[5:0:-1])   # reverse slicing

[ 6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[2 3 4 5]
[10  9  8  7  6  5  4  3  2  1]
[6 5 4 3 2]


In [ ]:
import numpy as np
s =[[1,2,3] , [3,4,5] , [5,6,7]]

s1 = np.array(s)
__builtins__.print(s1[1])
__builtins__.print(s1[2])
__builtins__.print(s1[-1])
__builtins__.print(s1[1][1])
s2=(s1+s1)
__builtins__.print(s2)
__builtins__.print([s1],[s1])
__builtins__.print(s1@s2)

[3 4 5]
[5 6 7]
[5 6 7]
4
[[ 2  4  6]
 [ 6  8 10]
 [10 12 14]]
[array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])] [array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])]
[[ 44  56  68]
 [ 80 104 128]
 [116 152 188]]
